[platformio]
default_envs = m5stack-basic
; default_envs = m5stack-atom-matrix
; default_envs = m5stack-atom-lite
; default_envs = m5stack-chain-dualkey

src_dir = examples/m5stack-sample

extra_configs = platformio-m5stack.ini

[env]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000

lib_extra_dirs = ../../src

build_flags = -DESP_NOW_CHANNEL=0
lib_deps =

lib_ldf_mode = deep

[build-target]
extends = release
; extends = debug

[release]
build_type = release
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=3
    -DLOG_LOCAL_LEVEL=3

[debug]
build_type = debug
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=4
    -DLOG_LOCAL_LEVEL=4
    -DDEBUG

[esp-now-manager]
extends = build-target
build_flags =
    ${env.build_flags}
    ${build-target.build_flags}
lib_deps =
    ${env.lib_deps}

[env:m5stack-basic]
extends = esp-now-manager, m5stack-basic-16MB
build_flags =
    ${esp-now-manager.build_flags}
    ${m5stack-basic-16MB.build_flags}
lib_deps =
    ${esp-now-manager.lib_deps}
    ${m5stack-basic-16MB.lib_deps}

[env:m5stack-atom-matrix]
extends = esp-now-manager, m5stack-atom-matrix
build_flags =
    ${esp-now-manager.build_flags}
    ${m5stack-atom-matrix.build_flags}
lib_deps =
    ${esp-now-manager.lib_deps}
    ${m5stack-atom-matrix.lib_deps}

[env:m5stack-atom-lite]
extends = esp-now-manager, m5stack-atom-lite
build_flags =
    ${esp-now-manager.build_flags}
    ${m5stack-atom-lite.build_flags}
lib_deps =
    ${esp-now-manager.lib_deps}
    ${m5stack-atom-lite.lib_deps}

[env:m5stack-chain-dualkey]
extends = esp-now-manager, m5stack-chain-dualkey
build_flags =
    ${esp-now-manager.build_flags}
    ${m5stack-chain-dualkey.build_flags}
lib_deps =
    ${esp-now-manager.lib_deps}
    ${m5stack-chain-dualkey.lib_deps}
